### ISSUE TITLE
Informative assert messages

### ISSUE THREAD

**Issue by wilzbach** [dragon-lang/dc#18]
i.e. rebasing https://github.com/dlang/dmd/pull/8517

**Comment by marler8997** [comment]
Can be merged anytime
* Makes the fork more appealing

**Comment by wilzbach** [comment]
This has been partially merged at mainline DMD now (druntime changes are still pending -https://github.com/dlang/druntime/pull/2413), though it's still behind a switch and will be so for probably a long time.

So I guess `-checkaction=context` is another of those flags which should be set by default.

**Comment by wilzbach** [comment]
Closing in favor of https://github.com/dragon-lang/dc/issues/76 as it's now just about flipping the default `dmd.globals` (or adding the flags in a wrapper).
