### ISSUE TITLE
Compiler error for humans

### ISSUE THREAD

**Issue by wilzbach** [dragon-lang/dc#19]
i.e. rebasing https://github.com/dlang/dmd/pull/8487

**Comment by marler8997** [comment]
Can be merged anytime
* Makes the fork more appealing

**Comment by marler8997** [comment]
Yeah we could do that. We'll need to setup a nightly build or a way to store CI output binaries so they can be downloaded.

**Comment by wilzbach** [comment]
Closing in favor of https://github.com/dragon-lang/dc/issues/76 as it's now just about flipping the default `dmd.globals` (or adding the flags in a wrapper).
